version: "3"

services:
  api:
    build: ./api
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=172.24.156.108
      - DB=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest